name: Docker actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build and run Docker container
      run: |
        docker build -t my-container .
        docker run -d --name my-app my-container
        
    - name: Execute command in Docker container
      run: |
        docker exec my-app /bin/ss -tulpn
        docker exec my-app ping -c 3 google.com > result.txt
        
    - name: Copy result file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: result.txt
        path: result.txt
